/*************************************************************
 * 
 *  #####   ###   #     #    #		 #     #####    #####     ####
 *    #			 #    #	#	  #			#		#			 #  #	  	#		#		 #
 *    #			 #    #		# #				#				 ###			#####    #		
 *    #			###   #		  #				#				 #   #		#					####
 *
 * order_server.h
 * Generated by tinyrpc framework tinyrpc_generator.py
 * Create Time: 2023-08-11 22:59:02
 * This file will be overwrite every time
*************************************************************/


#ifndef ORDER_SERVER_SERVICE_ORDER_SERVER_H 
#define ORDER_SERVER_SERVICE_ORDER_SERVER_H

#include <google/protobuf/service.h>
#include "order_server/pb/order_server.pb.h"

namespace order_server {

class OrderServiceImpl : public OrderService {

 public:

  OrderServiceImpl() = default;

  ~OrderServiceImpl() = default;

  // override from OrderService
  virtual void query_order_detail(::google::protobuf::RpcController* controller,
                       const ::queryOrderDetailReq* request,
                       ::queryOrderDetailRsp* response,
                       ::google::protobuf::Closure* done);

  // override from OrderService
  virtual void make_order(::google::protobuf::RpcController* controller,
                       const ::makeOrderReq* request,
                       ::makeOrderRsp* response,
                       ::google::protobuf::Closure* done);

  // override from OrderService
  virtual void delete_order(::google::protobuf::RpcController* controller,
                       const ::deleteOrderReq* request,
                       ::deleteOrderRsp* response,
                       ::google::protobuf::Closure* done);

  

};

}


#endif