/*************************************************************
 * 
 *  #####   ###   #     #    #		 #     #####    #####     ####
 *    #			 #    #	#	  #			#		#			 #  #	  	#		#		 #
 *    #			 #    #		# #				#				 ###			#####    #		
 *    #			###   #		  #				#				 #   #		#					####
 *
 * query_order_detail.h
 * Generated by tinyrpc framework tinyrpc_generator.py
 * Create Time: 2023-08-11 22:59:02
 * This file will not be overwrite althrough protobuf file changed !!!
 * Just write this file while not exist
*************************************************************/

#ifndef ORDER_SERVER_INTERFACE_QUERY_ORDER_DETAIL_H
#define ORDER_SERVER_INTERFACE_QUERY_ORDER_DETAIL_H 

#include "order_server/pb/order_server.pb.h"


namespace order_server {

/*
 * Rpc Interface Class
 * Alloc one object every time RPC call begin, and destroy this object while RPC call end
*/

class QueryOrderDetailInterface {
 public:

  QueryOrderDetailInterface(const ::queryOrderDetailReq& request, ::queryOrderDetailRsp& response);

  ~QueryOrderDetailInterface();

  void run();

 private:
  const ::queryOrderDetailReq& m_request;      // request object fron client

  ::queryOrderDetailRsp& m_response;           // response object that reply to client

};


}


#endif