/*************************************************************
 * 
 *  #####   ###   #     #    #		 #     #####    #####     ####
 *    #			 #    #	#	  #			#		#			 #  #	  	#		#		 #
 *    #			 #    #		# #				#				 ###			#####    #		
 *    #			###   #		  #				#				 #   #		#					####
 *
 * order_server.h
 * Generated by tinyrpc framework tinyrpc_generator.py
 * Create Time: 2023-08-11 22:59:02
 * This file will not be overwrite althrough protobuf file changed !!!
 * Just write this file while not exist
*************************************************************/


#include <google/protobuf/service.h>
#include "tinyrpc/comm/start.h"
#include "order_server/service/order_server.h"


int main(int argc, char* argv[]) {
  if (argc != 2) {
    printf("Start order_server server error, input argc is not 2!");
    printf("Start order_server like this: \n");
    printf("./order_server order_server.xml\n");
    return 0;
  }

  tinyrpc::InitConfig(argv[1]);

  REGISTER_SERVICE(order_server::OrderServiceImpl);

  tinyrpc::StartRpcServer();
  
  return 0;
}